### ISSUE TITLE
use tabs whitespace for output files

### ISSUE THREAD

**Issue by efx** [Turbo87/ember-mocha-codemods#2]
Thanks for building this; saving me hours in our project's 1900+ tests
Our project uses tabs for indentation; hence running the codemod command causes tons of linting errors. 
Could you point me to what files I should reindent to avoid this? I can add a caveat to the main README too.

**Comment by Turbo87** [comment]
@efx you should be able to call `jscodeshift` with `--printOptions` as described [here](https://github.com/cpojer/js-codemod#recast-options), but instead of setting the `quote` option you use [`useTabs`](https://github.com/benjamn/recast/blob/master/lib/options.js#L14)

**Comment by efx** [comment]
awesome, thanks! That resolved most of it but still seeing an indentation error for the newly inserted `setupTest`. I'll dig into it.
