### ISSUE TITLE
tracking latest API codemod quirks 

### ISSUE THREAD

**Issue by efx** [Turbo87/ember-mocha-codemods#27]
I've started testing #17 against my organization's codebase and will update this ticket with quirks I'm seeing.

- in some integration tests, `import '@ember/test-helpers';` gets introduced

**Comment by Turbo87** [comment]
@efx I think it would be best if you could open individual issues for the things we find, then it's easier to close them when fixed. example input files might also be good so that we can reproduce the issues.

**Comment by efx** [comment]
Closing in favor of #32.
