### ISSUE TITLE
render calls in before/beforeEach aren't converted

### ISSUE THREAD

**Issue by apellerano-pw** [Turbo87/ember-mocha-codemods#32]
Sometimes when tests have similar setups we use a `beforeEach` to call `render`. The codemod does a good job converting `it` usages to async functions but misses functions passed to other mocha hooks

**Comment by efx** [comment]
This sounds like the same issue in: https://github.com/Turbo87/ember-mocha-codemods/pull/26. would you mind confirming? I'm picking the codemod up again today to see if I can get it rewriting properly.

**Comment by apellerano-pw** [comment]
Yes it seems like the same issue to me. Thanks for making a fix!

**Comment by efx** [comment]
cool thanks! no problem. I think I may have fixed the issue here: https://github.com/efx/ember-mocha-codemods/tree/fix-14
If you have time,  you could try that branch against your codebase and let me know if you have any issues.

**Comment by apellerano-pw** [comment]
I ran it on a file, here is the before and after.

While it did convert the render to the one imported from `@ember/test-helpers`, it didn't add async or await to the calls so I don't think it would be a sufficient fix for my case

```javascript
beforeEach(function () {
  this.render(hbs`{{my-component
    isActiveCollection=true
    collection=collection
  }}`);
});
```

```javascript
beforeEach(function () {
  render(hbs`{{my-component
    isActiveCollection=true
    collection=collection
  }}`);
});
```

**Comment by apellerano-pw** [comment]
Here's an input file

```javascript
import { expect } from 'chai';
import {
  beforeEach,
  context,
  describe,
  it,
} from 'mocha';
import { setupComponentTest } from 'ember-mocha';
import hbs from 'htmlbars-inline-precompile';

describe('Integration | Component | my-component', function () {
  setupComponentTest('my-component', {
    integration: true,
  });

  context('when in some situation or another', function () {
    beforeEach(function () {
      this.render(hbs`{{my-component}}`);
    });

    it('should do the thing', function () {
      expect(true).to.be.true;
    });
  });
});
```
I ran it against this with
`jscodeshift -t https://raw.githubusercontent.com/efx/ember-mocha-codemods/fix-14/fourteen-testing-api.js fake-test.js`

**Comment by efx** [comment]
sweet, thanks for checking. I have found a few other bugs too. I will add this snippet above as a test too.

**Comment by efx** [comment]
@apellerano-pw I just updated the branch with a passing test accounting for the `context` hook. If it runs ok on your codebase, I'll open the PR.

**Comment by apellerano-pw** [comment]
ayyyy it worked! :tada:
![](https://media1.giphy.com/media/l2JeaXSlN7al98Kn6/giphy.gif?cid=e1bb72ff5b3694063669424e67bae6d5)

**Comment by efx** [comment]
good point.  I think a new ticket is best so we can keep the PR's smaller.

**Comment by apellerano-pw** [comment]
I made #37 for it
